# -*- coding: utf-8 -*-
"""NETFLIX ROTTEN TOMATOES

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1js8O-BCA8YuJqJ3ifn3GvQL0oLRK9iPG
"""

import numpy as np

import pandas as pd

import seaborn as sns

import matplotlib.pyplot as plt

import datetime as dt

# Commented out IPython magic to ensure Python compatibility.
# %matplotlib inline

from google.colab import files
uploaded = files.upload()

my=pd.read_csv('netflix-rotten-tomatoes-metacritic-imdb.csv')

my.head()

my.tail()

my.isnull().any()

my.dropna(inplace=True)

my.isnull().any()

my.head(40)

sns.pairplot(my)

my.columns

sns.boxplot(my['IMDb Score'])

my['IMDb Score']=my['IMDb Score'].clip(lower=my['IMDb Score'].quantile(0.05),upper=my['IMDb Score'].quantile(0.95))

sns.boxplot(my['IMDb Score'])

sns.boxplot(my['IMDb Votes'])

my['IMDb Votes']=my['IMDb Votes'].clip(lower=my['IMDb Votes'].quantile(0.10),upper=my['IMDb Votes'].quantile(0.90))

sns.boxplot(my['IMDb Votes'])

sns.boxplot(my['Rotten Tomatoes Score'])

my.describe()

my.shape

corr=my.corr()

sns.heatmap(corr,annot=True)

sns.boxplot(my['Hidden Gem Score'])

my['Hidden Gem Score']=my['Hidden Gem Score'].clip(lower=my['Hidden Gem Score'].quantile(0.15),upper=my['Hidden Gem Score'].quantile(0.85))

sns.boxplot(my['Hidden Gem Score'])

sns.boxplot(my['Awards Received'])

my['Awards Received']=my['Awards Received'].clip(lower=my['Awards Received'].quantile(0.15),upper=my['Awards Received'].quantile(0.85))

sns.boxplot(my['Awards Received'])

sns.boxplot(my['Awards Nominated For'])

my['Awards Nominated For']=my['Awards Nominated For'].clip(lower=my['Awards Nominated For'].quantile(0.15),upper=my['Awards Nominated For'].quantile(0.85))

sns.boxplot(my['Awards Nominated For'])

sns.countplot(my['Hidden Gem Score'])